DUEL_LINKS = "Yu-Gi-Oh! DUEL LINKS"

LEFT_MARGIN = 8
RIGHT_MARGIN = 8
TOP_MARGIN = 31
BOTTOM_MARGIN = 8

INITIATE_LEFT = 560
INITIATE_TOP = 420
INITIATE_RIGHT = INITIATE_LEFT + 160
INITIATE_BOTTOM = INITIATE_TOP + 35

INITIATE_POS = (INITIATE_RIGHT + INITIATE_LEFT) / 2, (INITIATE_TOP + INITIATE_BOTTOM) / 2
